name: Build and Release Tagged Version

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: pnpm install
      run: |
        pnpm install

    - name: pnpm lint
      run: |
        pnpm lint

    - name: Build Package Release
      run: |
        pnpm release

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN}}
