name: Lint Code and Verify

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 6.32.9
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    - name: install
      run: |
        pnpm install

    - name: lint
      run: |
        pnpm lint

    - name: Build Storybook
      run: |
        pnpm release-storybook

    - name: Build Package Release
      run: |
        pnpm release
